// Code generated by capnpc-go. DO NOT EDIT.

package bcpcnp

import (
	capnp "capnproto.org/go/capnp/v3"
	text "capnproto.org/go/capnp/v3/encoding/text"
	schemas "capnproto.org/go/capnp/v3/schemas"
)

type OID capnp.Struct

// OID_TypeID is the unique identifier for the type OID.
const OID_TypeID = 0xad94273f8795df75

func NewOID(s *capnp.Segment) (OID, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 16, PointerCount: 0})
	return OID(st), err
}

func NewRootOID(s *capnp.Segment) (OID, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 16, PointerCount: 0})
	return OID(st), err
}

func ReadRootOID(msg *capnp.Message) (OID, error) {
	root, err := msg.Root()
	return OID(root.Struct()), err
}

func (s OID) String() string {
	str, _ := text.Marshal(0xad94273f8795df75, capnp.Struct(s))
	return str
}

func (s OID) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (OID) DecodeFromPtr(p capnp.Ptr) OID {
	return OID(capnp.Struct{}.DecodeFromPtr(p))
}

func (s OID) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s OID) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s OID) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s OID) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s OID) W0() uint64 {
	return capnp.Struct(s).Uint64(0)
}

func (s OID) SetW0(v uint64) {
	capnp.Struct(s).SetUint64(0, v)
}

func (s OID) W1() uint64 {
	return capnp.Struct(s).Uint64(8)
}

func (s OID) SetW1(v uint64) {
	capnp.Struct(s).SetUint64(8, v)
}

// OID_List is a list of OID.
type OID_List = capnp.StructList[OID]

// NewOID creates a new list of OID.
func NewOID_List(s *capnp.Segment, sz int32) (OID_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 16, PointerCount: 0}, sz)
	return capnp.StructList[OID](l), err
}

// OID_Future is a wrapper for a OID promised by a client call.
type OID_Future struct{ *capnp.Future }

func (f OID_Future) Struct() (OID, error) {
	p, err := f.Future.Ptr()
	return OID(p.Struct()), err
}

type Handle capnp.Struct

// Handle_TypeID is the unique identifier for the type Handle.
const Handle_TypeID = 0xf69d2f252c16e80b

func NewHandle(s *capnp.Segment) (Handle, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 16, PointerCount: 1})
	return Handle(st), err
}

func NewRootHandle(s *capnp.Segment) (Handle, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 16, PointerCount: 1})
	return Handle(st), err
}

func ReadRootHandle(msg *capnp.Message) (Handle, error) {
	root, err := msg.Root()
	return Handle(root.Struct()), err
}

func (s Handle) String() string {
	str, _ := text.Marshal(0xf69d2f252c16e80b, capnp.Struct(s))
	return str
}

func (s Handle) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (Handle) DecodeFromPtr(p capnp.Ptr) Handle {
	return Handle(capnp.Struct{}.DecodeFromPtr(p))
}

func (s Handle) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s Handle) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Handle) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Handle) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s Handle) Target() (OID, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return OID(p.Struct()), err
}

func (s Handle) HasTarget() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s Handle) SetTarget(v OID) error {
	return capnp.Struct(s).SetPtr(0, capnp.Struct(v).ToPtr())
}

// NewTarget sets the target field to a newly
// allocated OID struct, preferring placement in s's segment.
func (s Handle) NewTarget() (OID, error) {
	ss, err := NewOID(capnp.Struct(s).Segment())
	if err != nil {
		return OID{}, err
	}
	err = capnp.Struct(s).SetPtr(0, capnp.Struct(ss).ToPtr())
	return ss, err
}

func (s Handle) Secret0() uint64 {
	return capnp.Struct(s).Uint64(0)
}

func (s Handle) SetSecret0(v uint64) {
	capnp.Struct(s).SetUint64(0, v)
}

func (s Handle) Secret1() uint64 {
	return capnp.Struct(s).Uint64(8)
}

func (s Handle) SetSecret1(v uint64) {
	capnp.Struct(s).SetUint64(8, v)
}

// Handle_List is a list of Handle.
type Handle_List = capnp.StructList[Handle]

// NewHandle creates a new list of Handle.
func NewHandle_List(s *capnp.Segment, sz int32) (Handle_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 16, PointerCount: 1}, sz)
	return capnp.StructList[Handle](l), err
}

// Handle_Future is a wrapper for a Handle promised by a client call.
type Handle_Future struct{ *capnp.Future }

func (f Handle_Future) Struct() (Handle, error) {
	p, err := f.Future.Ptr()
	return Handle(p.Struct()), err
}
func (p Handle_Future) Target() OID_Future {
	return OID_Future{Future: p.Future.Field(0, nil)}
}

type CID capnp.Struct

// CID_TypeID is the unique identifier for the type CID.
const CID_TypeID = 0xcecb8fb9ee5403cb

func NewCID(s *capnp.Segment) (CID, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 32, PointerCount: 0})
	return CID(st), err
}

func NewRootCID(s *capnp.Segment) (CID, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 32, PointerCount: 0})
	return CID(st), err
}

func ReadRootCID(msg *capnp.Message) (CID, error) {
	root, err := msg.Root()
	return CID(root.Struct()), err
}

func (s CID) String() string {
	str, _ := text.Marshal(0xcecb8fb9ee5403cb, capnp.Struct(s))
	return str
}

func (s CID) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (CID) DecodeFromPtr(p capnp.Ptr) CID {
	return CID(capnp.Struct{}.DecodeFromPtr(p))
}

func (s CID) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s CID) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s CID) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s CID) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s CID) W0() uint64 {
	return capnp.Struct(s).Uint64(0)
}

func (s CID) SetW0(v uint64) {
	capnp.Struct(s).SetUint64(0, v)
}

func (s CID) W1() uint64 {
	return capnp.Struct(s).Uint64(8)
}

func (s CID) SetW1(v uint64) {
	capnp.Struct(s).SetUint64(8, v)
}

func (s CID) W2() uint64 {
	return capnp.Struct(s).Uint64(16)
}

func (s CID) SetW2(v uint64) {
	capnp.Struct(s).SetUint64(16, v)
}

func (s CID) W3() uint64 {
	return capnp.Struct(s).Uint64(24)
}

func (s CID) SetW3(v uint64) {
	capnp.Struct(s).SetUint64(24, v)
}

// CID_List is a list of CID.
type CID_List = capnp.StructList[CID]

// NewCID creates a new list of CID.
func NewCID_List(s *capnp.Segment, sz int32) (CID_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 32, PointerCount: 0}, sz)
	return capnp.StructList[CID](l), err
}

// CID_Future is a wrapper for a CID promised by a client call.
type CID_Future struct{ *capnp.Future }

func (f CID_Future) Struct() (CID, error) {
	p, err := f.Future.Ptr()
	return CID(p.Struct()), err
}

type GetReq capnp.Struct

// GetReq_TypeID is the unique identifier for the type GetReq.
const GetReq_TypeID = 0xc7392f6d4c1e5fa4

func NewGetReq(s *capnp.Segment) (GetReq, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 2})
	return GetReq(st), err
}

func NewRootGetReq(s *capnp.Segment) (GetReq, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 2})
	return GetReq(st), err
}

func ReadRootGetReq(msg *capnp.Message) (GetReq, error) {
	root, err := msg.Root()
	return GetReq(root.Struct()), err
}

func (s GetReq) String() string {
	str, _ := text.Marshal(0xc7392f6d4c1e5fa4, capnp.Struct(s))
	return str
}

func (s GetReq) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (GetReq) DecodeFromPtr(p capnp.Ptr) GetReq {
	return GetReq(capnp.Struct{}.DecodeFromPtr(p))
}

func (s GetReq) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s GetReq) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s GetReq) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s GetReq) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s GetReq) Tx() (Handle, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return Handle(p.Struct()), err
}

func (s GetReq) HasTx() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s GetReq) SetTx(v Handle) error {
	return capnp.Struct(s).SetPtr(0, capnp.Struct(v).ToPtr())
}

// NewTx sets the tx field to a newly
// allocated Handle struct, preferring placement in s's segment.
func (s GetReq) NewTx() (Handle, error) {
	ss, err := NewHandle(capnp.Struct(s).Segment())
	if err != nil {
		return Handle{}, err
	}
	err = capnp.Struct(s).SetPtr(0, capnp.Struct(ss).ToPtr())
	return ss, err
}

func (s GetReq) Cid() (CID, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return CID(p.Struct()), err
}

func (s GetReq) HasCid() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s GetReq) SetCid(v CID) error {
	return capnp.Struct(s).SetPtr(1, capnp.Struct(v).ToPtr())
}

// NewCid sets the cid field to a newly
// allocated CID struct, preferring placement in s's segment.
func (s GetReq) NewCid() (CID, error) {
	ss, err := NewCID(capnp.Struct(s).Segment())
	if err != nil {
		return CID{}, err
	}
	err = capnp.Struct(s).SetPtr(1, capnp.Struct(ss).ToPtr())
	return ss, err
}

func (s GetReq) MaxSize() uint32 {
	return capnp.Struct(s).Uint32(0)
}

func (s GetReq) SetMaxSize(v uint32) {
	capnp.Struct(s).SetUint32(0, v)
}

// GetReq_List is a list of GetReq.
type GetReq_List = capnp.StructList[GetReq]

// NewGetReq creates a new list of GetReq.
func NewGetReq_List(s *capnp.Segment, sz int32) (GetReq_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 8, PointerCount: 2}, sz)
	return capnp.StructList[GetReq](l), err
}

// GetReq_Future is a wrapper for a GetReq promised by a client call.
type GetReq_Future struct{ *capnp.Future }

func (f GetReq_Future) Struct() (GetReq, error) {
	p, err := f.Future.Ptr()
	return GetReq(p.Struct()), err
}
func (p GetReq_Future) Tx() Handle_Future {
	return Handle_Future{Future: p.Future.Field(0, nil)}
}
func (p GetReq_Future) Cid() CID_Future {
	return CID_Future{Future: p.Future.Field(1, nil)}
}

type GetResp capnp.Struct

// GetResp_TypeID is the unique identifier for the type GetResp.
const GetResp_TypeID = 0x8da84a724ae86f7b

func NewGetResp(s *capnp.Segment) (GetResp, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return GetResp(st), err
}

func NewRootGetResp(s *capnp.Segment) (GetResp, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return GetResp(st), err
}

func ReadRootGetResp(msg *capnp.Message) (GetResp, error) {
	root, err := msg.Root()
	return GetResp(root.Struct()), err
}

func (s GetResp) String() string {
	str, _ := text.Marshal(0x8da84a724ae86f7b, capnp.Struct(s))
	return str
}

func (s GetResp) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (GetResp) DecodeFromPtr(p capnp.Ptr) GetResp {
	return GetResp(capnp.Struct{}.DecodeFromPtr(p))
}

func (s GetResp) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s GetResp) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s GetResp) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s GetResp) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s GetResp) Data() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return []byte(p.Data()), err
}

func (s GetResp) HasData() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s GetResp) SetData(v []byte) error {
	return capnp.Struct(s).SetData(0, v)
}

// GetResp_List is a list of GetResp.
type GetResp_List = capnp.StructList[GetResp]

// NewGetResp creates a new list of GetResp.
func NewGetResp_List(s *capnp.Segment, sz int32) (GetResp_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1}, sz)
	return capnp.StructList[GetResp](l), err
}

// GetResp_Future is a wrapper for a GetResp promised by a client call.
type GetResp_Future struct{ *capnp.Future }

func (f GetResp_Future) Struct() (GetResp, error) {
	p, err := f.Future.Ptr()
	return GetResp(p.Struct()), err
}

type PostReq capnp.Struct

// PostReq_TypeID is the unique identifier for the type PostReq.
const PostReq_TypeID = 0xaf92061cc8c62299

func NewPostReq(s *capnp.Segment) (PostReq, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2})
	return PostReq(st), err
}

func NewRootPostReq(s *capnp.Segment) (PostReq, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2})
	return PostReq(st), err
}

func ReadRootPostReq(msg *capnp.Message) (PostReq, error) {
	root, err := msg.Root()
	return PostReq(root.Struct()), err
}

func (s PostReq) String() string {
	str, _ := text.Marshal(0xaf92061cc8c62299, capnp.Struct(s))
	return str
}

func (s PostReq) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (PostReq) DecodeFromPtr(p capnp.Ptr) PostReq {
	return PostReq(capnp.Struct{}.DecodeFromPtr(p))
}

func (s PostReq) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s PostReq) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s PostReq) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s PostReq) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s PostReq) Volume() (Handle, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return Handle(p.Struct()), err
}

func (s PostReq) HasVolume() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s PostReq) SetVolume(v Handle) error {
	return capnp.Struct(s).SetPtr(0, capnp.Struct(v).ToPtr())
}

// NewVolume sets the volume field to a newly
// allocated Handle struct, preferring placement in s's segment.
func (s PostReq) NewVolume() (Handle, error) {
	ss, err := NewHandle(capnp.Struct(s).Segment())
	if err != nil {
		return Handle{}, err
	}
	err = capnp.Struct(s).SetPtr(0, capnp.Struct(ss).ToPtr())
	return ss, err
}

func (s PostReq) Data() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return []byte(p.Data()), err
}

func (s PostReq) HasData() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s PostReq) SetData(v []byte) error {
	return capnp.Struct(s).SetData(1, v)
}

// PostReq_List is a list of PostReq.
type PostReq_List = capnp.StructList[PostReq]

// NewPostReq creates a new list of PostReq.
func NewPostReq_List(s *capnp.Segment, sz int32) (PostReq_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2}, sz)
	return capnp.StructList[PostReq](l), err
}

// PostReq_Future is a wrapper for a PostReq promised by a client call.
type PostReq_Future struct{ *capnp.Future }

func (f PostReq_Future) Struct() (PostReq, error) {
	p, err := f.Future.Ptr()
	return PostReq(p.Struct()), err
}
func (p PostReq_Future) Volume() Handle_Future {
	return Handle_Future{Future: p.Future.Field(0, nil)}
}

type PostResp capnp.Struct

// PostResp_TypeID is the unique identifier for the type PostResp.
const PostResp_TypeID = 0xedbc105190fbefad

func NewPostResp(s *capnp.Segment) (PostResp, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return PostResp(st), err
}

func NewRootPostResp(s *capnp.Segment) (PostResp, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return PostResp(st), err
}

func ReadRootPostResp(msg *capnp.Message) (PostResp, error) {
	root, err := msg.Root()
	return PostResp(root.Struct()), err
}

func (s PostResp) String() string {
	str, _ := text.Marshal(0xedbc105190fbefad, capnp.Struct(s))
	return str
}

func (s PostResp) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (PostResp) DecodeFromPtr(p capnp.Ptr) PostResp {
	return PostResp(capnp.Struct{}.DecodeFromPtr(p))
}

func (s PostResp) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s PostResp) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s PostResp) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s PostResp) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s PostResp) Cid() (CID, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return CID(p.Struct()), err
}

func (s PostResp) HasCid() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s PostResp) SetCid(v CID) error {
	return capnp.Struct(s).SetPtr(0, capnp.Struct(v).ToPtr())
}

// NewCid sets the cid field to a newly
// allocated CID struct, preferring placement in s's segment.
func (s PostResp) NewCid() (CID, error) {
	ss, err := NewCID(capnp.Struct(s).Segment())
	if err != nil {
		return CID{}, err
	}
	err = capnp.Struct(s).SetPtr(0, capnp.Struct(ss).ToPtr())
	return ss, err
}

// PostResp_List is a list of PostResp.
type PostResp_List = capnp.StructList[PostResp]

// NewPostResp creates a new list of PostResp.
func NewPostResp_List(s *capnp.Segment, sz int32) (PostResp_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1}, sz)
	return capnp.StructList[PostResp](l), err
}

// PostResp_Future is a wrapper for a PostResp promised by a client call.
type PostResp_Future struct{ *capnp.Future }

func (f PostResp_Future) Struct() (PostResp, error) {
	p, err := f.Future.Ptr()
	return PostResp(p.Struct()), err
}
func (p PostResp_Future) Cid() CID_Future {
	return CID_Future{Future: p.Future.Field(0, nil)}
}

const schema_e77f58556e08090d = "x\xdatS?h\x13q\x18\xfd\xde\xef\xbb\xb6i5" +
	"x\xc7\x05\x07\xf1\x0f\x16\x8bZZ\xdb\xaa\x8bYRk" +
	"\x8bMi\xb1\xbf\xda\x82\x83\xa0gr\xd8@\xfe\\\x93" +
	"\xab):t\x14\x0ab\x09:(\xb89\xb8\x84\xe0\xe0" +
	" 8\xabPT\x1c\x9c\x1d\xdbE\xc5A\x17\x87\x93_" +
	"\x92\xde\x85K\xb2\xbd|\xbc\xef}\xef\xbd\xfbe|\x1b" +
	"\x93\xdaD\xf4\x0b\x93\x90#=\xbd\xde\x83\xc2\xde\\q" +
	"\xee\xd5#2\x06\xe0E\xfb#\xf9\x95\x1b\x9b\xbb\xd4\x83" +
	">\"\xf3\x13*\xe6\xb7:\xfa\x8a\x04\xc1[\xff\xfe\xf4" +
	"a\xe2\xf4\x93*\xc9\x01\x88\x80\xac)\xc6o\x14\xcd?" +
	"h\xa02\xc1{6\xf8\xfe\xe3\xd1\xdeJ-\xa4+\x14" +
	"cAT\xcc\x95:\x92Bq_\xde:>\x9f\x1b\xbb" +
	"\xf4A\xe9\xb6\x91\xabb\xcb|SG\xafE\x8d\xe0\xed" +
	"\xf0\xf2\xcf\xb7\x8fw>+\xb2\x162\x91\xe4\xa2\xb9\xc0" +
	"\x0d\xb4K\xf0\xaa\xbf\xfemK\xfd\xdd\x8fN\xe1\x8ei" +
	"\xcf\xcd\xa1\xfa\xd6IM\x85;\xb0wxdh\xec\xc5" +
	"\xdfP\xb8\x06\xf9\xb2\xb6e&\xeb\xe4\x19\xadF\xa3\xde" +
	"\x9d\x94s.e9y8\xf1\xab\xb6\xbbd\x97\xe0," +
	"\x02Rc\x8dH\x03\x91\x11\x1d&\x92\x11\x86\x8c\x09\x1c" +
	"J[\xae\x85(\x09D\x09\xfe*\x9dp\xe2\xd7\x92\xd3" +
	"j-\xe2\xaf\x9d=B$O1\xe4\xb8\x80\x01\xc4\xa0" +
	"\x86\xa3jx\x86!/\x0apy\x1c\xfd$\xd0O\xe0" +
	"\xf2\xc4>l\xf5\xb3X(\xb9K6\xd6B\xc2\xf1N" +
	"\xc2\xc3\x81p\xe2^!\xbb\x9e\xb3\xa1\x07E\x10\xa0S" +
	"\x17\xf7\xfb\xc1\xd7\x88\xd4\xa1\x83\xfe\xa1\x19ev\x92!" +
	"\xe7[\x0e%\x07\x89\xe44C.\x0a@\xc4 \x88\x8c" +
	"\x85)\"9\xcb\x90\xcb\x02\xecn\xb4\x1f\xeeKe\xd2" +
	"\xd0\x83\xef\xdd\x98n\xe6\xac\x8d\xeb\x99\xfb6\"$\x10" +
	"\x09\xf5y\xa5\xd1\xa7\xee\xbb\xb1\x94\x9b\x9b\x0c\xb9\xda\xe2" +
	"\xc6V\xc3\xdb\x0c\x99\x150D\xd3NF\x0d\xd3\x0c\xe9" +
	"\x08\x18\xcc10\x91\x91S\xc3U\x86t\xbb5\xcf\xe5" +
	"\xf3\x01\xbc\xd0\xfd{p)\xfc@\x06\x83\x07\xd29i" +
	"\xab\xc8\xac\x95Og\xed\xb6\xae\xe3A\xd7~\xd5SA" +
	"\xd5\x86@{\xd7\x09\xd7*\xde\xb5]\xe8\xc1\xdf\xb9\xd9" +
	"l\xc9N\x15m\xd7O\xd9\xfc\xedG\xfd\x1f\x00\x00\xff" +
	"\xffG\x0a\xdb\""

func RegisterSchema(reg *schemas.Registry) {
	reg.Register(&schemas.Schema{
		String: schema_e77f58556e08090d,
		Nodes: []uint64{
			0x8da84a724ae86f7b,
			0xad94273f8795df75,
			0xaf92061cc8c62299,
			0xc7392f6d4c1e5fa4,
			0xcecb8fb9ee5403cb,
			0xedbc105190fbefad,
			0xf69d2f252c16e80b,
		},
		Compressed: true,
	})
}
