// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.13.0
// source: bcproto.proto

package bcproto

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

// PeerRouting
type RoutingTag struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DstId []byte   `protobuf:"bytes,1,opt,name=dst_id,json=dstId,proto3" json:"dst_id,omitempty"`
	Path  []uint64 `protobuf:"varint,2,rep,packed,name=path,proto3" json:"path,omitempty"`
}

func (x *RoutingTag) Reset() {
	*x = RoutingTag{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bcproto_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoutingTag) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoutingTag) ProtoMessage() {}

func (x *RoutingTag) ProtoReflect() protoreflect.Message {
	mi := &file_bcproto_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoutingTag.ProtoReflect.Descriptor instead.
func (*RoutingTag) Descriptor() ([]byte, []int) {
	return file_bcproto_proto_rawDescGZIP(), []int{0}
}

func (x *RoutingTag) GetDstId() []byte {
	if x != nil {
		return x.DstId
	}
	return nil
}

func (x *RoutingTag) GetPath() []uint64 {
	if x != nil {
		return x.Path
	}
	return nil
}

type ListPeersReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoutingTag *RoutingTag `protobuf:"bytes,1,opt,name=routing_tag,json=routingTag,proto3" json:"routing_tag,omitempty"`
}

func (x *ListPeersReq) Reset() {
	*x = ListPeersReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bcproto_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListPeersReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPeersReq) ProtoMessage() {}

func (x *ListPeersReq) ProtoReflect() protoreflect.Message {
	mi := &file_bcproto_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPeersReq.ProtoReflect.Descriptor instead.
func (*ListPeersReq) Descriptor() ([]byte, []int) {
	return file_bcproto_proto_rawDescGZIP(), []int{1}
}

func (x *ListPeersReq) GetRoutingTag() *RoutingTag {
	if x != nil {
		return x.RoutingTag
	}
	return nil
}

type ListPeersRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PeerId    []byte      `protobuf:"bytes,1,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	PeerInfos []*PeerInfo `protobuf:"bytes,2,rep,name=peer_infos,json=peerInfos,proto3" json:"peer_infos,omitempty"`
}

func (x *ListPeersRes) Reset() {
	*x = ListPeersRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bcproto_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListPeersRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPeersRes) ProtoMessage() {}

func (x *ListPeersRes) ProtoReflect() protoreflect.Message {
	mi := &file_bcproto_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPeersRes.ProtoReflect.Descriptor instead.
func (*ListPeersRes) Descriptor() ([]byte, []int) {
	return file_bcproto_proto_rawDescGZIP(), []int{2}
}

func (x *ListPeersRes) GetPeerId() []byte {
	if x != nil {
		return x.PeerId
	}
	return nil
}

func (x *ListPeersRes) GetPeerInfos() []*PeerInfo {
	if x != nil {
		return x.PeerInfos
	}
	return nil
}

type PeerInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   []byte   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Path []uint64 `protobuf:"varint,2,rep,packed,name=path,proto3" json:"path,omitempty"`
}

func (x *PeerInfo) Reset() {
	*x = PeerInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bcproto_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PeerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerInfo) ProtoMessage() {}

func (x *PeerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_bcproto_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerInfo.ProtoReflect.Descriptor instead.
func (*PeerInfo) Descriptor() ([]byte, []int) {
	return file_bcproto_proto_rawDescGZIP(), []int{3}
}

func (x *PeerInfo) GetId() []byte {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *PeerInfo) GetPath() []uint64 {
	if x != nil {
		return x.Path
	}
	return nil
}

// BlobRouting
type ListBlobsReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoutingTag *RoutingTag `protobuf:"bytes,1,opt,name=routing_tag,json=routingTag,proto3" json:"routing_tag,omitempty"`
	Prefix     []byte      `protobuf:"bytes,2,opt,name=prefix,proto3" json:"prefix,omitempty"`
}

func (x *ListBlobsReq) Reset() {
	*x = ListBlobsReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bcproto_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListBlobsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBlobsReq) ProtoMessage() {}

func (x *ListBlobsReq) ProtoReflect() protoreflect.Message {
	mi := &file_bcproto_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBlobsReq.ProtoReflect.Descriptor instead.
func (*ListBlobsReq) Descriptor() ([]byte, []int) {
	return file_bcproto_proto_rawDescGZIP(), []int{4}
}

func (x *ListBlobsReq) GetRoutingTag() *RoutingTag {
	if x != nil {
		return x.RoutingTag
	}
	return nil
}

func (x *ListBlobsReq) GetPrefix() []byte {
	if x != nil {
		return x.Prefix
	}
	return nil
}

type ListBlobsRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BlobLocs []*BlobLoc `protobuf:"bytes,1,rep,name=blob_locs,json=blobLocs,proto3" json:"blob_locs,omitempty"`
	TooMany  bool       `protobuf:"varint,2,opt,name=too_many,json=tooMany,proto3" json:"too_many,omitempty"`
}

func (x *ListBlobsRes) Reset() {
	*x = ListBlobsRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bcproto_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListBlobsRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBlobsRes) ProtoMessage() {}

func (x *ListBlobsRes) ProtoReflect() protoreflect.Message {
	mi := &file_bcproto_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBlobsRes.ProtoReflect.Descriptor instead.
func (*ListBlobsRes) Descriptor() ([]byte, []int) {
	return file_bcproto_proto_rawDescGZIP(), []int{5}
}

func (x *ListBlobsRes) GetBlobLocs() []*BlobLoc {
	if x != nil {
		return x.BlobLocs
	}
	return nil
}

func (x *ListBlobsRes) GetTooMany() bool {
	if x != nil {
		return x.TooMany
	}
	return false
}

type BlobLoc struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BlobId    []byte `protobuf:"bytes,1,opt,name=blob_id,json=blobId,proto3" json:"blob_id,omitempty"`
	PeerId    []byte `protobuf:"bytes,2,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	SightedAt uint64 `protobuf:"varint,3,opt,name=sighted_at,json=sightedAt,proto3" json:"sighted_at,omitempty"`
}

func (x *BlobLoc) Reset() {
	*x = BlobLoc{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bcproto_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BlobLoc) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlobLoc) ProtoMessage() {}

func (x *BlobLoc) ProtoReflect() protoreflect.Message {
	mi := &file_bcproto_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlobLoc.ProtoReflect.Descriptor instead.
func (*BlobLoc) Descriptor() ([]byte, []int) {
	return file_bcproto_proto_rawDescGZIP(), []int{6}
}

func (x *BlobLoc) GetBlobId() []byte {
	if x != nil {
		return x.BlobId
	}
	return nil
}

func (x *BlobLoc) GetPeerId() []byte {
	if x != nil {
		return x.PeerId
	}
	return nil
}

func (x *BlobLoc) GetSightedAt() uint64 {
	if x != nil {
		return x.SightedAt
	}
	return 0
}

// Fetching
type GetReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoutingTag *RoutingTag `protobuf:"bytes,1,opt,name=routing_tag,json=routingTag,proto3" json:"routing_tag,omitempty"`
	BlobId     []byte      `protobuf:"bytes,2,opt,name=blob_id,json=blobId,proto3" json:"blob_id,omitempty"`
	HashAlgo   uint32      `protobuf:"varint,3,opt,name=hash_algo,json=hashAlgo,proto3" json:"hash_algo,omitempty"`
	Found      bool        `protobuf:"varint,4,opt,name=found,proto3" json:"found,omitempty"`
}

func (x *GetReq) Reset() {
	*x = GetReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bcproto_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReq) ProtoMessage() {}

func (x *GetReq) ProtoReflect() protoreflect.Message {
	mi := &file_bcproto_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReq.ProtoReflect.Descriptor instead.
func (*GetReq) Descriptor() ([]byte, []int) {
	return file_bcproto_proto_rawDescGZIP(), []int{7}
}

func (x *GetReq) GetRoutingTag() *RoutingTag {
	if x != nil {
		return x.RoutingTag
	}
	return nil
}

func (x *GetReq) GetBlobId() []byte {
	if x != nil {
		return x.BlobId
	}
	return nil
}

func (x *GetReq) GetHashAlgo() uint32 {
	if x != nil {
		return x.HashAlgo
	}
	return 0
}

func (x *GetReq) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

type GetRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BlobId []byte `protobuf:"bytes,1,opt,name=blob_id,json=blobId,proto3" json:"blob_id,omitempty"`
	// Types that are assignable to Res:
	//	*GetRes_Data
	//	*GetRes_Redirect
	Res isGetRes_Res `protobuf_oneof:"res"`
}

func (x *GetRes) Reset() {
	*x = GetRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bcproto_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRes) ProtoMessage() {}

func (x *GetRes) ProtoReflect() protoreflect.Message {
	mi := &file_bcproto_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRes.ProtoReflect.Descriptor instead.
func (*GetRes) Descriptor() ([]byte, []int) {
	return file_bcproto_proto_rawDescGZIP(), []int{8}
}

func (x *GetRes) GetBlobId() []byte {
	if x != nil {
		return x.BlobId
	}
	return nil
}

func (m *GetRes) GetRes() isGetRes_Res {
	if m != nil {
		return m.Res
	}
	return nil
}

func (x *GetRes) GetData() []byte {
	if x, ok := x.GetRes().(*GetRes_Data); ok {
		return x.Data
	}
	return nil
}

func (x *GetRes) GetRedirect() *GetReq {
	if x, ok := x.GetRes().(*GetRes_Redirect); ok {
		return x.Redirect
	}
	return nil
}

type isGetRes_Res interface {
	isGetRes_Res()
}

type GetRes_Data struct {
	Data []byte `protobuf:"bytes,2,opt,name=data,proto3,oneof"`
}

type GetRes_Redirect struct {
	Redirect *GetReq `protobuf:"bytes,3,opt,name=redirect,proto3,oneof"`
}

func (*GetRes_Data) isGetRes_Res() {}

func (*GetRes_Redirect) isGetRes_Res() {}

var File_bcproto_proto protoreflect.FileDescriptor

var file_bcproto_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x62, 0x63, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x37, 0x0a, 0x0a, 0x52, 0x6f, 0x75, 0x74, 0x69, 0x6e, 0x67, 0x54, 0x61, 0x67, 0x12, 0x15, 0x0a,
	0x06, 0x64, 0x73, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x64,
	0x73, 0x74, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x74, 0x68, 0x18, 0x02, 0x20, 0x03,
	0x28, 0x04, 0x52, 0x04, 0x70, 0x61, 0x74, 0x68, 0x22, 0x3c, 0x0a, 0x0c, 0x4c, 0x69, 0x73, 0x74,
	0x50, 0x65, 0x65, 0x72, 0x73, 0x52, 0x65, 0x71, 0x12, 0x2c, 0x0a, 0x0b, 0x72, 0x6f, 0x75, 0x74,
	0x69, 0x6e, 0x67, 0x5f, 0x74, 0x61, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e,
	0x52, 0x6f, 0x75, 0x74, 0x69, 0x6e, 0x67, 0x54, 0x61, 0x67, 0x52, 0x0a, 0x72, 0x6f, 0x75, 0x74,
	0x69, 0x6e, 0x67, 0x54, 0x61, 0x67, 0x22, 0x51, 0x0a, 0x0c, 0x4c, 0x69, 0x73, 0x74, 0x50, 0x65,
	0x65, 0x72, 0x73, 0x52, 0x65, 0x73, 0x12, 0x17, 0x0a, 0x07, 0x70, 0x65, 0x65, 0x72, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x70, 0x65, 0x65, 0x72, 0x49, 0x64, 0x12,
	0x28, 0x0a, 0x0a, 0x70, 0x65, 0x65, 0x72, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x73, 0x18, 0x02, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x50, 0x65, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x09,
	0x70, 0x65, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x73, 0x22, 0x2e, 0x0a, 0x08, 0x50, 0x65, 0x65,
	0x72, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x74, 0x68, 0x18, 0x02, 0x20,
	0x03, 0x28, 0x04, 0x52, 0x04, 0x70, 0x61, 0x74, 0x68, 0x22, 0x54, 0x0a, 0x0c, 0x4c, 0x69, 0x73,
	0x74, 0x42, 0x6c, 0x6f, 0x62, 0x73, 0x52, 0x65, 0x71, 0x12, 0x2c, 0x0a, 0x0b, 0x72, 0x6f, 0x75,
	0x74, 0x69, 0x6e, 0x67, 0x5f, 0x74, 0x61, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b,
	0x2e, 0x52, 0x6f, 0x75, 0x74, 0x69, 0x6e, 0x67, 0x54, 0x61, 0x67, 0x52, 0x0a, 0x72, 0x6f, 0x75,
	0x74, 0x69, 0x6e, 0x67, 0x54, 0x61, 0x67, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x72, 0x65, 0x66, 0x69,
	0x78, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x70, 0x72, 0x65, 0x66, 0x69, 0x78, 0x22,
	0x50, 0x0a, 0x0c, 0x4c, 0x69, 0x73, 0x74, 0x42, 0x6c, 0x6f, 0x62, 0x73, 0x52, 0x65, 0x73, 0x12,
	0x25, 0x0a, 0x09, 0x62, 0x6c, 0x6f, 0x62, 0x5f, 0x6c, 0x6f, 0x63, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x08, 0x2e, 0x42, 0x6c, 0x6f, 0x62, 0x4c, 0x6f, 0x63, 0x52, 0x08, 0x62, 0x6c,
	0x6f, 0x62, 0x4c, 0x6f, 0x63, 0x73, 0x12, 0x19, 0x0a, 0x08, 0x74, 0x6f, 0x6f, 0x5f, 0x6d, 0x61,
	0x6e, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x74, 0x6f, 0x6f, 0x4d, 0x61, 0x6e,
	0x79, 0x22, 0x5a, 0x0a, 0x07, 0x42, 0x6c, 0x6f, 0x62, 0x4c, 0x6f, 0x63, 0x12, 0x17, 0x0a, 0x07,
	0x62, 0x6c, 0x6f, 0x62, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x62,
	0x6c, 0x6f, 0x62, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x70, 0x65, 0x65, 0x72, 0x5f, 0x69, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x70, 0x65, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1d,
	0x0a, 0x0a, 0x73, 0x69, 0x67, 0x68, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x09, 0x73, 0x69, 0x67, 0x68, 0x74, 0x65, 0x64, 0x41, 0x74, 0x22, 0x82, 0x01,
	0x0a, 0x06, 0x47, 0x65, 0x74, 0x52, 0x65, 0x71, 0x12, 0x2c, 0x0a, 0x0b, 0x72, 0x6f, 0x75, 0x74,
	0x69, 0x6e, 0x67, 0x5f, 0x74, 0x61, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e,
	0x52, 0x6f, 0x75, 0x74, 0x69, 0x6e, 0x67, 0x54, 0x61, 0x67, 0x52, 0x0a, 0x72, 0x6f, 0x75, 0x74,
	0x69, 0x6e, 0x67, 0x54, 0x61, 0x67, 0x12, 0x17, 0x0a, 0x07, 0x62, 0x6c, 0x6f, 0x62, 0x5f, 0x69,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x62, 0x6c, 0x6f, 0x62, 0x49, 0x64, 0x12,
	0x1b, 0x0a, 0x09, 0x68, 0x61, 0x73, 0x68, 0x5f, 0x61, 0x6c, 0x67, 0x6f, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x08, 0x68, 0x61, 0x73, 0x68, 0x41, 0x6c, 0x67, 0x6f, 0x12, 0x14, 0x0a, 0x05,
	0x66, 0x6f, 0x75, 0x6e, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x66, 0x6f, 0x75,
	0x6e, 0x64, 0x22, 0x65, 0x0a, 0x06, 0x47, 0x65, 0x74, 0x52, 0x65, 0x73, 0x12, 0x17, 0x0a, 0x07,
	0x62, 0x6c, 0x6f, 0x62, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x62,
	0x6c, 0x6f, 0x62, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0c, 0x48, 0x00, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x25, 0x0a, 0x08, 0x72,
	0x65, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x07, 0x2e,
	0x47, 0x65, 0x74, 0x52, 0x65, 0x71, 0x48, 0x00, 0x52, 0x08, 0x72, 0x65, 0x64, 0x69, 0x72, 0x65,
	0x63, 0x74, 0x42, 0x05, 0x0a, 0x03, 0x72, 0x65, 0x73, 0x42, 0x34, 0x5a, 0x32, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x62, 0x6c, 0x6f, 0x62, 0x63, 0x61, 0x63, 0x68,
	0x65, 0x2f, 0x62, 0x6c, 0x6f, 0x62, 0x63, 0x61, 0x63, 0x68, 0x65, 0x2f, 0x70, 0x6b, 0x67, 0x2f,
	0x62, 0x6c, 0x6f, 0x62, 0x6e, 0x65, 0x74, 0x2f, 0x62, 0x63, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_bcproto_proto_rawDescOnce sync.Once
	file_bcproto_proto_rawDescData = file_bcproto_proto_rawDesc
)

func file_bcproto_proto_rawDescGZIP() []byte {
	file_bcproto_proto_rawDescOnce.Do(func() {
		file_bcproto_proto_rawDescData = protoimpl.X.CompressGZIP(file_bcproto_proto_rawDescData)
	})
	return file_bcproto_proto_rawDescData
}

var file_bcproto_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_bcproto_proto_goTypes = []interface{}{
	(*RoutingTag)(nil),   // 0: RoutingTag
	(*ListPeersReq)(nil), // 1: ListPeersReq
	(*ListPeersRes)(nil), // 2: ListPeersRes
	(*PeerInfo)(nil),     // 3: PeerInfo
	(*ListBlobsReq)(nil), // 4: ListBlobsReq
	(*ListBlobsRes)(nil), // 5: ListBlobsRes
	(*BlobLoc)(nil),      // 6: BlobLoc
	(*GetReq)(nil),       // 7: GetReq
	(*GetRes)(nil),       // 8: GetRes
}
var file_bcproto_proto_depIdxs = []int32{
	0, // 0: ListPeersReq.routing_tag:type_name -> RoutingTag
	3, // 1: ListPeersRes.peer_infos:type_name -> PeerInfo
	0, // 2: ListBlobsReq.routing_tag:type_name -> RoutingTag
	6, // 3: ListBlobsRes.blob_locs:type_name -> BlobLoc
	0, // 4: GetReq.routing_tag:type_name -> RoutingTag
	7, // 5: GetRes.redirect:type_name -> GetReq
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_bcproto_proto_init() }
func file_bcproto_proto_init() {
	if File_bcproto_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_bcproto_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoutingTag); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bcproto_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListPeersReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bcproto_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListPeersRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bcproto_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PeerInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bcproto_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListBlobsReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bcproto_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListBlobsRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bcproto_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BlobLoc); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bcproto_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bcproto_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_bcproto_proto_msgTypes[8].OneofWrappers = []interface{}{
		(*GetRes_Data)(nil),
		(*GetRes_Redirect)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_bcproto_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_bcproto_proto_goTypes,
		DependencyIndexes: file_bcproto_proto_depIdxs,
		MessageInfos:      file_bcproto_proto_msgTypes,
	}.Build()
	File_bcproto_proto = out.File
	file_bcproto_proto_rawDesc = nil
	file_bcproto_proto_goTypes = nil
	file_bcproto_proto_depIdxs = nil
}
