// Code generated by protoc-gen-go. DO NOT EDIT.
// source: blobnet.proto

package blobnet

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// PeerRouting
type RoutingTag struct {
	DstId                []byte   `protobuf:"bytes,1,opt,name=dst_id,json=dstId,proto3" json:"dst_id,omitempty"`
	Path                 []uint64 `protobuf:"varint,2,rep,packed,name=path,proto3" json:"path,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RoutingTag) Reset()         { *m = RoutingTag{} }
func (m *RoutingTag) String() string { return proto.CompactTextString(m) }
func (*RoutingTag) ProtoMessage()    {}
func (*RoutingTag) Descriptor() ([]byte, []int) {
	return fileDescriptor_bff037fc68412930, []int{0}
}

func (m *RoutingTag) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoutingTag.Unmarshal(m, b)
}
func (m *RoutingTag) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoutingTag.Marshal(b, m, deterministic)
}
func (m *RoutingTag) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoutingTag.Merge(m, src)
}
func (m *RoutingTag) XXX_Size() int {
	return xxx_messageInfo_RoutingTag.Size(m)
}
func (m *RoutingTag) XXX_DiscardUnknown() {
	xxx_messageInfo_RoutingTag.DiscardUnknown(m)
}

var xxx_messageInfo_RoutingTag proto.InternalMessageInfo

func (m *RoutingTag) GetDstId() []byte {
	if m != nil {
		return m.DstId
	}
	return nil
}

func (m *RoutingTag) GetPath() []uint64 {
	if m != nil {
		return m.Path
	}
	return nil
}

type ListPeersReq struct {
	RoutingTag           *RoutingTag `protobuf:"bytes,1,opt,name=routing_tag,json=routingTag,proto3" json:"routing_tag,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ListPeersReq) Reset()         { *m = ListPeersReq{} }
func (m *ListPeersReq) String() string { return proto.CompactTextString(m) }
func (*ListPeersReq) ProtoMessage()    {}
func (*ListPeersReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_bff037fc68412930, []int{1}
}

func (m *ListPeersReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListPeersReq.Unmarshal(m, b)
}
func (m *ListPeersReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListPeersReq.Marshal(b, m, deterministic)
}
func (m *ListPeersReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListPeersReq.Merge(m, src)
}
func (m *ListPeersReq) XXX_Size() int {
	return xxx_messageInfo_ListPeersReq.Size(m)
}
func (m *ListPeersReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ListPeersReq.DiscardUnknown(m)
}

var xxx_messageInfo_ListPeersReq proto.InternalMessageInfo

func (m *ListPeersReq) GetRoutingTag() *RoutingTag {
	if m != nil {
		return m.RoutingTag
	}
	return nil
}

type ListPeersRes struct {
	PeerId               []byte      `protobuf:"bytes,1,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	PeerInfos            []*PeerInfo `protobuf:"bytes,2,rep,name=peer_infos,json=peerInfos,proto3" json:"peer_infos,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ListPeersRes) Reset()         { *m = ListPeersRes{} }
func (m *ListPeersRes) String() string { return proto.CompactTextString(m) }
func (*ListPeersRes) ProtoMessage()    {}
func (*ListPeersRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_bff037fc68412930, []int{2}
}

func (m *ListPeersRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListPeersRes.Unmarshal(m, b)
}
func (m *ListPeersRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListPeersRes.Marshal(b, m, deterministic)
}
func (m *ListPeersRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListPeersRes.Merge(m, src)
}
func (m *ListPeersRes) XXX_Size() int {
	return xxx_messageInfo_ListPeersRes.Size(m)
}
func (m *ListPeersRes) XXX_DiscardUnknown() {
	xxx_messageInfo_ListPeersRes.DiscardUnknown(m)
}

var xxx_messageInfo_ListPeersRes proto.InternalMessageInfo

func (m *ListPeersRes) GetPeerId() []byte {
	if m != nil {
		return m.PeerId
	}
	return nil
}

func (m *ListPeersRes) GetPeerInfos() []*PeerInfo {
	if m != nil {
		return m.PeerInfos
	}
	return nil
}

type PeerInfo struct {
	Id                   []byte   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Path                 []uint64 `protobuf:"varint,2,rep,packed,name=path,proto3" json:"path,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PeerInfo) Reset()         { *m = PeerInfo{} }
func (m *PeerInfo) String() string { return proto.CompactTextString(m) }
func (*PeerInfo) ProtoMessage()    {}
func (*PeerInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_bff037fc68412930, []int{3}
}

func (m *PeerInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PeerInfo.Unmarshal(m, b)
}
func (m *PeerInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PeerInfo.Marshal(b, m, deterministic)
}
func (m *PeerInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PeerInfo.Merge(m, src)
}
func (m *PeerInfo) XXX_Size() int {
	return xxx_messageInfo_PeerInfo.Size(m)
}
func (m *PeerInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_PeerInfo.DiscardUnknown(m)
}

var xxx_messageInfo_PeerInfo proto.InternalMessageInfo

func (m *PeerInfo) GetId() []byte {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *PeerInfo) GetPath() []uint64 {
	if m != nil {
		return m.Path
	}
	return nil
}

// BlobRouting
type ListBlobsReq struct {
	RoutingTag           *RoutingTag `protobuf:"bytes,1,opt,name=routing_tag,json=routingTag,proto3" json:"routing_tag,omitempty"`
	Prefix               []byte      `protobuf:"bytes,2,opt,name=prefix,proto3" json:"prefix,omitempty"`
	HashAlgo             []byte      `protobuf:"bytes,3,opt,name=hash_algo,json=hashAlgo,proto3" json:"hash_algo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ListBlobsReq) Reset()         { *m = ListBlobsReq{} }
func (m *ListBlobsReq) String() string { return proto.CompactTextString(m) }
func (*ListBlobsReq) ProtoMessage()    {}
func (*ListBlobsReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_bff037fc68412930, []int{4}
}

func (m *ListBlobsReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListBlobsReq.Unmarshal(m, b)
}
func (m *ListBlobsReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListBlobsReq.Marshal(b, m, deterministic)
}
func (m *ListBlobsReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListBlobsReq.Merge(m, src)
}
func (m *ListBlobsReq) XXX_Size() int {
	return xxx_messageInfo_ListBlobsReq.Size(m)
}
func (m *ListBlobsReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ListBlobsReq.DiscardUnknown(m)
}

var xxx_messageInfo_ListBlobsReq proto.InternalMessageInfo

func (m *ListBlobsReq) GetRoutingTag() *RoutingTag {
	if m != nil {
		return m.RoutingTag
	}
	return nil
}

func (m *ListBlobsReq) GetPrefix() []byte {
	if m != nil {
		return m.Prefix
	}
	return nil
}

func (m *ListBlobsReq) GetHashAlgo() []byte {
	if m != nil {
		return m.HashAlgo
	}
	return nil
}

type ListBlobsRes struct {
	TrieHash []byte `protobuf:"bytes,1,opt,name=trie_hash,json=trieHash,proto3" json:"trie_hash,omitempty"`
	// Types that are valid to be assigned to Res:
	//	*ListBlobsRes_TooMany
	//	*ListBlobsRes_BlobList
	Res                  isListBlobsRes_Res `protobuf_oneof:"res"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *ListBlobsRes) Reset()         { *m = ListBlobsRes{} }
func (m *ListBlobsRes) String() string { return proto.CompactTextString(m) }
func (*ListBlobsRes) ProtoMessage()    {}
func (*ListBlobsRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_bff037fc68412930, []int{5}
}

func (m *ListBlobsRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListBlobsRes.Unmarshal(m, b)
}
func (m *ListBlobsRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListBlobsRes.Marshal(b, m, deterministic)
}
func (m *ListBlobsRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListBlobsRes.Merge(m, src)
}
func (m *ListBlobsRes) XXX_Size() int {
	return xxx_messageInfo_ListBlobsRes.Size(m)
}
func (m *ListBlobsRes) XXX_DiscardUnknown() {
	xxx_messageInfo_ListBlobsRes.DiscardUnknown(m)
}

var xxx_messageInfo_ListBlobsRes proto.InternalMessageInfo

func (m *ListBlobsRes) GetTrieHash() []byte {
	if m != nil {
		return m.TrieHash
	}
	return nil
}

type isListBlobsRes_Res interface {
	isListBlobsRes_Res()
}

type ListBlobsRes_TooMany struct {
	TooMany bool `protobuf:"varint,2,opt,name=too_many,json=tooMany,proto3,oneof"`
}

type ListBlobsRes_BlobList struct {
	BlobList *BlobList `protobuf:"bytes,3,opt,name=blob_list,json=blobList,proto3,oneof"`
}

func (*ListBlobsRes_TooMany) isListBlobsRes_Res() {}

func (*ListBlobsRes_BlobList) isListBlobsRes_Res() {}

func (m *ListBlobsRes) GetRes() isListBlobsRes_Res {
	if m != nil {
		return m.Res
	}
	return nil
}

func (m *ListBlobsRes) GetTooMany() bool {
	if x, ok := m.GetRes().(*ListBlobsRes_TooMany); ok {
		return x.TooMany
	}
	return false
}

func (m *ListBlobsRes) GetBlobList() *BlobList {
	if x, ok := m.GetRes().(*ListBlobsRes_BlobList); ok {
		return x.BlobList
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*ListBlobsRes) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*ListBlobsRes_TooMany)(nil),
		(*ListBlobsRes_BlobList)(nil),
	}
}

type BlobList struct {
	Claims               []*BlobClaim `protobuf:"bytes,1,rep,name=claims,proto3" json:"claims,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *BlobList) Reset()         { *m = BlobList{} }
func (m *BlobList) String() string { return proto.CompactTextString(m) }
func (*BlobList) ProtoMessage()    {}
func (*BlobList) Descriptor() ([]byte, []int) {
	return fileDescriptor_bff037fc68412930, []int{6}
}

func (m *BlobList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlobList.Unmarshal(m, b)
}
func (m *BlobList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlobList.Marshal(b, m, deterministic)
}
func (m *BlobList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlobList.Merge(m, src)
}
func (m *BlobList) XXX_Size() int {
	return xxx_messageInfo_BlobList.Size(m)
}
func (m *BlobList) XXX_DiscardUnknown() {
	xxx_messageInfo_BlobList.DiscardUnknown(m)
}

var xxx_messageInfo_BlobList proto.InternalMessageInfo

func (m *BlobList) GetClaims() []*BlobClaim {
	if m != nil {
		return m.Claims
	}
	return nil
}

type BlobClaim struct {
	BlobId               []byte   `protobuf:"bytes,1,opt,name=blob_id,json=blobId,proto3" json:"blob_id,omitempty"`
	ExpiresAt            int64    `protobuf:"varint,2,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BlobClaim) Reset()         { *m = BlobClaim{} }
func (m *BlobClaim) String() string { return proto.CompactTextString(m) }
func (*BlobClaim) ProtoMessage()    {}
func (*BlobClaim) Descriptor() ([]byte, []int) {
	return fileDescriptor_bff037fc68412930, []int{7}
}

func (m *BlobClaim) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlobClaim.Unmarshal(m, b)
}
func (m *BlobClaim) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlobClaim.Marshal(b, m, deterministic)
}
func (m *BlobClaim) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlobClaim.Merge(m, src)
}
func (m *BlobClaim) XXX_Size() int {
	return xxx_messageInfo_BlobClaim.Size(m)
}
func (m *BlobClaim) XXX_DiscardUnknown() {
	xxx_messageInfo_BlobClaim.DiscardUnknown(m)
}

var xxx_messageInfo_BlobClaim proto.InternalMessageInfo

func (m *BlobClaim) GetBlobId() []byte {
	if m != nil {
		return m.BlobId
	}
	return nil
}

func (m *BlobClaim) GetExpiresAt() int64 {
	if m != nil {
		return m.ExpiresAt
	}
	return 0
}

type BlobLoc struct {
	BlobId               []byte   `protobuf:"bytes,1,opt,name=blob_id,json=blobId,proto3" json:"blob_id,omitempty"`
	PeerId               []byte   `protobuf:"bytes,2,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	ExpiresAt            int64    `protobuf:"varint,3,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BlobLoc) Reset()         { *m = BlobLoc{} }
func (m *BlobLoc) String() string { return proto.CompactTextString(m) }
func (*BlobLoc) ProtoMessage()    {}
func (*BlobLoc) Descriptor() ([]byte, []int) {
	return fileDescriptor_bff037fc68412930, []int{8}
}

func (m *BlobLoc) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlobLoc.Unmarshal(m, b)
}
func (m *BlobLoc) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlobLoc.Marshal(b, m, deterministic)
}
func (m *BlobLoc) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlobLoc.Merge(m, src)
}
func (m *BlobLoc) XXX_Size() int {
	return xxx_messageInfo_BlobLoc.Size(m)
}
func (m *BlobLoc) XXX_DiscardUnknown() {
	xxx_messageInfo_BlobLoc.DiscardUnknown(m)
}

var xxx_messageInfo_BlobLoc proto.InternalMessageInfo

func (m *BlobLoc) GetBlobId() []byte {
	if m != nil {
		return m.BlobId
	}
	return nil
}

func (m *BlobLoc) GetPeerId() []byte {
	if m != nil {
		return m.PeerId
	}
	return nil
}

func (m *BlobLoc) GetExpiresAt() int64 {
	if m != nil {
		return m.ExpiresAt
	}
	return 0
}

// Fetching
type GetReq struct {
	RoutingTag           *RoutingTag `protobuf:"bytes,1,opt,name=routing_tag,json=routingTag,proto3" json:"routing_tag,omitempty"`
	BlobId               []byte      `protobuf:"bytes,2,opt,name=blob_id,json=blobId,proto3" json:"blob_id,omitempty"`
	HashAlgo             uint32      `protobuf:"varint,3,opt,name=hash_algo,json=hashAlgo,proto3" json:"hash_algo,omitempty"`
	Found                bool        `protobuf:"varint,4,opt,name=found,proto3" json:"found,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *GetReq) Reset()         { *m = GetReq{} }
func (m *GetReq) String() string { return proto.CompactTextString(m) }
func (*GetReq) ProtoMessage()    {}
func (*GetReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_bff037fc68412930, []int{9}
}

func (m *GetReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetReq.Unmarshal(m, b)
}
func (m *GetReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetReq.Marshal(b, m, deterministic)
}
func (m *GetReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetReq.Merge(m, src)
}
func (m *GetReq) XXX_Size() int {
	return xxx_messageInfo_GetReq.Size(m)
}
func (m *GetReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetReq proto.InternalMessageInfo

func (m *GetReq) GetRoutingTag() *RoutingTag {
	if m != nil {
		return m.RoutingTag
	}
	return nil
}

func (m *GetReq) GetBlobId() []byte {
	if m != nil {
		return m.BlobId
	}
	return nil
}

func (m *GetReq) GetHashAlgo() uint32 {
	if m != nil {
		return m.HashAlgo
	}
	return 0
}

func (m *GetReq) GetFound() bool {
	if m != nil {
		return m.Found
	}
	return false
}

type GetRes struct {
	BlobId []byte `protobuf:"bytes,1,opt,name=blob_id,json=blobId,proto3" json:"blob_id,omitempty"`
	// Types that are valid to be assigned to Res:
	//	*GetRes_Data
	//	*GetRes_Redirect
	Res                  isGetRes_Res `protobuf_oneof:"res"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *GetRes) Reset()         { *m = GetRes{} }
func (m *GetRes) String() string { return proto.CompactTextString(m) }
func (*GetRes) ProtoMessage()    {}
func (*GetRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_bff037fc68412930, []int{10}
}

func (m *GetRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRes.Unmarshal(m, b)
}
func (m *GetRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRes.Marshal(b, m, deterministic)
}
func (m *GetRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRes.Merge(m, src)
}
func (m *GetRes) XXX_Size() int {
	return xxx_messageInfo_GetRes.Size(m)
}
func (m *GetRes) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRes.DiscardUnknown(m)
}

var xxx_messageInfo_GetRes proto.InternalMessageInfo

func (m *GetRes) GetBlobId() []byte {
	if m != nil {
		return m.BlobId
	}
	return nil
}

type isGetRes_Res interface {
	isGetRes_Res()
}

type GetRes_Data struct {
	Data []byte `protobuf:"bytes,2,opt,name=data,proto3,oneof"`
}

type GetRes_Redirect struct {
	Redirect *GetReq `protobuf:"bytes,3,opt,name=redirect,proto3,oneof"`
}

func (*GetRes_Data) isGetRes_Res() {}

func (*GetRes_Redirect) isGetRes_Res() {}

func (m *GetRes) GetRes() isGetRes_Res {
	if m != nil {
		return m.Res
	}
	return nil
}

func (m *GetRes) GetData() []byte {
	if x, ok := m.GetRes().(*GetRes_Data); ok {
		return x.Data
	}
	return nil
}

func (m *GetRes) GetRedirect() *GetReq {
	if x, ok := m.GetRes().(*GetRes_Redirect); ok {
		return x.Redirect
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*GetRes) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*GetRes_Data)(nil),
		(*GetRes_Redirect)(nil),
	}
}

func init() {
	proto.RegisterType((*RoutingTag)(nil), "RoutingTag")
	proto.RegisterType((*ListPeersReq)(nil), "ListPeersReq")
	proto.RegisterType((*ListPeersRes)(nil), "ListPeersRes")
	proto.RegisterType((*PeerInfo)(nil), "PeerInfo")
	proto.RegisterType((*ListBlobsReq)(nil), "ListBlobsReq")
	proto.RegisterType((*ListBlobsRes)(nil), "ListBlobsRes")
	proto.RegisterType((*BlobList)(nil), "BlobList")
	proto.RegisterType((*BlobClaim)(nil), "BlobClaim")
	proto.RegisterType((*BlobLoc)(nil), "BlobLoc")
	proto.RegisterType((*GetReq)(nil), "GetReq")
	proto.RegisterType((*GetRes)(nil), "GetRes")
}

func init() { proto.RegisterFile("blobnet.proto", fileDescriptor_bff037fc68412930) }

var fileDescriptor_bff037fc68412930 = []byte{
	// 459 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x53, 0xb1, 0x6e, 0xdb, 0x30,
	0x10, 0xb5, 0x25, 0x5b, 0x96, 0xce, 0x49, 0x07, 0x22, 0x6d, 0x05, 0x04, 0x05, 0x02, 0x02, 0x05,
	0x3c, 0x14, 0x1a, 0xd2, 0xa1, 0x4b, 0x97, 0x24, 0x43, 0x6d, 0xa0, 0x05, 0x5a, 0xa2, 0x53, 0x17,
	0x81, 0x32, 0x69, 0x99, 0x80, 0x22, 0x2a, 0xe4, 0x05, 0x88, 0xd7, 0x7e, 0x79, 0x41, 0x8a, 0xb6,
	0xa3, 0xb6, 0x19, 0xbc, 0xdd, 0xbd, 0xd3, 0xbd, 0xf7, 0x8e, 0x0f, 0x82, 0xf3, 0xaa, 0xd1, 0x55,
	0x2b, 0xb1, 0xe8, 0x8c, 0x46, 0x4d, 0x3f, 0x01, 0x30, 0xfd, 0x88, 0xaa, 0xad, 0x7f, 0xf2, 0x9a,
	0xbc, 0x86, 0x44, 0x58, 0x2c, 0x95, 0xc8, 0xc7, 0x57, 0xe3, 0xc5, 0x19, 0x9b, 0x0a, 0x8b, 0x2b,
	0x41, 0x08, 0x4c, 0x3a, 0x8e, 0xdb, 0x3c, 0xba, 0x8a, 0x17, 0x13, 0xe6, 0x6b, 0xfa, 0x19, 0xce,
	0xbe, 0x2a, 0x8b, 0xdf, 0xa5, 0x34, 0x96, 0xc9, 0x07, 0xf2, 0x01, 0xe6, 0xa6, 0x27, 0x2a, 0x91,
	0xd7, 0x7e, 0x7f, 0x7e, 0x3d, 0x2f, 0x8e, 0xe4, 0x0c, 0xcc, 0xa1, 0xa6, 0x3f, 0x06, 0xdb, 0x96,
	0xbc, 0x85, 0x59, 0x27, 0xa5, 0x39, 0x2a, 0x27, 0xae, 0x5d, 0x09, 0xb2, 0x00, 0xe8, 0x07, 0xed,
	0x46, 0x5b, 0x6f, 0x60, 0x7e, 0x9d, 0x15, 0x6e, 0x6f, 0xd5, 0x6e, 0x34, 0xcb, 0xba, 0x50, 0x59,
	0x5a, 0x40, 0xba, 0x87, 0xc9, 0x2b, 0x88, 0x0e, 0x4c, 0x91, 0xfa, 0xff, 0x01, 0x0f, 0xbd, 0x85,
	0xdb, 0x46, 0x57, 0xa7, 0x1f, 0x40, 0xde, 0x40, 0xd2, 0x19, 0xb9, 0x51, 0x4f, 0x79, 0x14, 0xfc,
	0xfa, 0x8e, 0x5c, 0x42, 0xb6, 0xe5, 0x76, 0x5b, 0xf2, 0xa6, 0xd6, 0x79, 0xec, 0x47, 0xa9, 0x03,
	0x6e, 0x9a, 0x5a, 0xd3, 0xdd, 0x40, 0xd2, 0xba, 0x8f, 0xd1, 0x28, 0x59, 0xba, 0x0f, 0x82, 0xdb,
	0xd4, 0x01, 0x4b, 0x6e, 0xb7, 0xe4, 0x12, 0x52, 0xd4, 0xba, 0xbc, 0xe7, 0xed, 0xce, 0x6b, 0xa4,
	0xcb, 0x11, 0x9b, 0xa1, 0xd6, 0xdf, 0x78, 0xbb, 0x23, 0x0b, 0xc8, 0x5c, 0x8e, 0x65, 0xa3, 0x2c,
	0x7a, 0x19, 0xf7, 0x2a, 0x8e, 0xd7, 0xf1, 0x2f, 0x47, 0x2c, 0xad, 0x42, 0x7d, 0x3b, 0x85, 0xd8,
	0x48, 0xff, 0x3a, 0xfb, 0x31, 0xa1, 0x90, 0xac, 0x1b, 0xae, 0xee, 0x6d, 0x3e, 0xf6, 0xef, 0x09,
	0x7e, 0xf3, 0xce, 0x41, 0x2c, 0x4c, 0xe8, 0x1d, 0x64, 0x07, 0xd0, 0xa5, 0xe3, 0xd5, 0x8e, 0xe9,
	0xb8, 0x76, 0x25, 0xc8, 0x3b, 0x00, 0xf9, 0xd4, 0x29, 0x23, 0x6d, 0xc9, 0xd1, 0xbb, 0x8c, 0x59,
	0x16, 0x90, 0x1b, 0xa4, 0xbf, 0x60, 0xe6, 0x45, 0xf5, 0xfa, 0x65, 0x8a, 0x67, 0xc9, 0x47, 0x83,
	0xe4, 0x87, 0xdc, 0xf1, 0xdf, 0xdc, 0xbf, 0xc7, 0x90, 0x7c, 0x91, 0x78, 0x7a, 0x72, 0xcf, 0x9c,
	0x44, 0x03, 0x27, 0xff, 0x44, 0x77, 0x7e, 0x8c, 0x8e, 0x5c, 0xc0, 0x74, 0xa3, 0x1f, 0x5b, 0x91,
	0x4f, 0x5c, 0x14, 0xac, 0x6f, 0xa8, 0x0c, 0x1e, 0xec, 0xcb, 0xf7, 0x5d, 0xc0, 0x44, 0x70, 0xe4,
	0xbd, 0xd6, 0x72, 0xc4, 0x7c, 0x47, 0xde, 0x43, 0x6a, 0xa4, 0x50, 0x46, 0xae, 0xf7, 0xf1, 0xcd,
	0x8a, 0xfe, 0x1a, 0x17, 0xde, 0x7e, 0x14, 0xc2, 0xab, 0x12, 0xff, 0xaf, 0x7e, 0xfc, 0x13, 0x00,
	0x00, 0xff, 0xff, 0x5b, 0x91, 0x56, 0xc4, 0xbc, 0x03, 0x00, 0x00,
}
