// Code generated by protoc-gen-go. DO NOT EDIT.
// source: blobnet.proto

package blobnet

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Router
type RoutingTag struct {
	DstId                []byte   `protobuf:"bytes,1,opt,name=dst_id,json=dstId,proto3" json:"dst_id,omitempty"`
	Path                 []uint64 `protobuf:"varint,2,rep,packed,name=path,proto3" json:"path,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RoutingTag) Reset()         { *m = RoutingTag{} }
func (m *RoutingTag) String() string { return proto.CompactTextString(m) }
func (*RoutingTag) ProtoMessage()    {}
func (*RoutingTag) Descriptor() ([]byte, []int) {
	return fileDescriptor_bff037fc68412930, []int{0}
}

func (m *RoutingTag) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoutingTag.Unmarshal(m, b)
}
func (m *RoutingTag) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoutingTag.Marshal(b, m, deterministic)
}
func (m *RoutingTag) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoutingTag.Merge(m, src)
}
func (m *RoutingTag) XXX_Size() int {
	return xxx_messageInfo_RoutingTag.Size(m)
}
func (m *RoutingTag) XXX_DiscardUnknown() {
	xxx_messageInfo_RoutingTag.DiscardUnknown(m)
}

var xxx_messageInfo_RoutingTag proto.InternalMessageInfo

func (m *RoutingTag) GetDstId() []byte {
	if m != nil {
		return m.DstId
	}
	return nil
}

func (m *RoutingTag) GetPath() []uint64 {
	if m != nil {
		return m.Path
	}
	return nil
}

type ListPeersReq struct {
	RoutingTag           *RoutingTag `protobuf:"bytes,1,opt,name=routing_tag,json=routingTag,proto3" json:"routing_tag,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ListPeersReq) Reset()         { *m = ListPeersReq{} }
func (m *ListPeersReq) String() string { return proto.CompactTextString(m) }
func (*ListPeersReq) ProtoMessage()    {}
func (*ListPeersReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_bff037fc68412930, []int{1}
}

func (m *ListPeersReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListPeersReq.Unmarshal(m, b)
}
func (m *ListPeersReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListPeersReq.Marshal(b, m, deterministic)
}
func (m *ListPeersReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListPeersReq.Merge(m, src)
}
func (m *ListPeersReq) XXX_Size() int {
	return xxx_messageInfo_ListPeersReq.Size(m)
}
func (m *ListPeersReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ListPeersReq.DiscardUnknown(m)
}

var xxx_messageInfo_ListPeersReq proto.InternalMessageInfo

func (m *ListPeersReq) GetRoutingTag() *RoutingTag {
	if m != nil {
		return m.RoutingTag
	}
	return nil
}

type ListPeersRes struct {
	PeerId               []byte      `protobuf:"bytes,1,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	PeerInfos            []*PeerInfo `protobuf:"bytes,2,rep,name=peer_infos,json=peerInfos,proto3" json:"peer_infos,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ListPeersRes) Reset()         { *m = ListPeersRes{} }
func (m *ListPeersRes) String() string { return proto.CompactTextString(m) }
func (*ListPeersRes) ProtoMessage()    {}
func (*ListPeersRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_bff037fc68412930, []int{2}
}

func (m *ListPeersRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListPeersRes.Unmarshal(m, b)
}
func (m *ListPeersRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListPeersRes.Marshal(b, m, deterministic)
}
func (m *ListPeersRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListPeersRes.Merge(m, src)
}
func (m *ListPeersRes) XXX_Size() int {
	return xxx_messageInfo_ListPeersRes.Size(m)
}
func (m *ListPeersRes) XXX_DiscardUnknown() {
	xxx_messageInfo_ListPeersRes.DiscardUnknown(m)
}

var xxx_messageInfo_ListPeersRes proto.InternalMessageInfo

func (m *ListPeersRes) GetPeerId() []byte {
	if m != nil {
		return m.PeerId
	}
	return nil
}

func (m *ListPeersRes) GetPeerInfos() []*PeerInfo {
	if m != nil {
		return m.PeerInfos
	}
	return nil
}

type PeerInfo struct {
	Id                   []byte   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Path                 []uint64 `protobuf:"varint,2,rep,packed,name=path,proto3" json:"path,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PeerInfo) Reset()         { *m = PeerInfo{} }
func (m *PeerInfo) String() string { return proto.CompactTextString(m) }
func (*PeerInfo) ProtoMessage()    {}
func (*PeerInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_bff037fc68412930, []int{3}
}

func (m *PeerInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PeerInfo.Unmarshal(m, b)
}
func (m *PeerInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PeerInfo.Marshal(b, m, deterministic)
}
func (m *PeerInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PeerInfo.Merge(m, src)
}
func (m *PeerInfo) XXX_Size() int {
	return xxx_messageInfo_PeerInfo.Size(m)
}
func (m *PeerInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_PeerInfo.DiscardUnknown(m)
}

var xxx_messageInfo_PeerInfo proto.InternalMessageInfo

func (m *PeerInfo) GetId() []byte {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *PeerInfo) GetPath() []uint64 {
	if m != nil {
		return m.Path
	}
	return nil
}

// Indexer
type ListBlobsReq struct {
	RoutingTag           *RoutingTag `protobuf:"bytes,1,opt,name=routing_tag,json=routingTag,proto3" json:"routing_tag,omitempty"`
	Prefix               []byte      `protobuf:"bytes,2,opt,name=prefix,proto3" json:"prefix,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ListBlobsReq) Reset()         { *m = ListBlobsReq{} }
func (m *ListBlobsReq) String() string { return proto.CompactTextString(m) }
func (*ListBlobsReq) ProtoMessage()    {}
func (*ListBlobsReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_bff037fc68412930, []int{4}
}

func (m *ListBlobsReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListBlobsReq.Unmarshal(m, b)
}
func (m *ListBlobsReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListBlobsReq.Marshal(b, m, deterministic)
}
func (m *ListBlobsReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListBlobsReq.Merge(m, src)
}
func (m *ListBlobsReq) XXX_Size() int {
	return xxx_messageInfo_ListBlobsReq.Size(m)
}
func (m *ListBlobsReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ListBlobsReq.DiscardUnknown(m)
}

var xxx_messageInfo_ListBlobsReq proto.InternalMessageInfo

func (m *ListBlobsReq) GetRoutingTag() *RoutingTag {
	if m != nil {
		return m.RoutingTag
	}
	return nil
}

func (m *ListBlobsReq) GetPrefix() []byte {
	if m != nil {
		return m.Prefix
	}
	return nil
}

type ListBlobsRes struct {
	TooMany              bool       `protobuf:"varint,1,opt,name=too_many,json=tooMany,proto3" json:"too_many,omitempty"`
	BlobLocs             []*BlobLoc `protobuf:"bytes,2,rep,name=blob_locs,json=blobLocs,proto3" json:"blob_locs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ListBlobsRes) Reset()         { *m = ListBlobsRes{} }
func (m *ListBlobsRes) String() string { return proto.CompactTextString(m) }
func (*ListBlobsRes) ProtoMessage()    {}
func (*ListBlobsRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_bff037fc68412930, []int{5}
}

func (m *ListBlobsRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListBlobsRes.Unmarshal(m, b)
}
func (m *ListBlobsRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListBlobsRes.Marshal(b, m, deterministic)
}
func (m *ListBlobsRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListBlobsRes.Merge(m, src)
}
func (m *ListBlobsRes) XXX_Size() int {
	return xxx_messageInfo_ListBlobsRes.Size(m)
}
func (m *ListBlobsRes) XXX_DiscardUnknown() {
	xxx_messageInfo_ListBlobsRes.DiscardUnknown(m)
}

var xxx_messageInfo_ListBlobsRes proto.InternalMessageInfo

func (m *ListBlobsRes) GetTooMany() bool {
	if m != nil {
		return m.TooMany
	}
	return false
}

func (m *ListBlobsRes) GetBlobLocs() []*BlobLoc {
	if m != nil {
		return m.BlobLocs
	}
	return nil
}

type BlobLoc struct {
	BlobId               []byte   `protobuf:"bytes,1,opt,name=blob_id,json=blobId,proto3" json:"blob_id,omitempty"`
	PeerId               []byte   `protobuf:"bytes,2,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BlobLoc) Reset()         { *m = BlobLoc{} }
func (m *BlobLoc) String() string { return proto.CompactTextString(m) }
func (*BlobLoc) ProtoMessage()    {}
func (*BlobLoc) Descriptor() ([]byte, []int) {
	return fileDescriptor_bff037fc68412930, []int{6}
}

func (m *BlobLoc) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlobLoc.Unmarshal(m, b)
}
func (m *BlobLoc) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlobLoc.Marshal(b, m, deterministic)
}
func (m *BlobLoc) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlobLoc.Merge(m, src)
}
func (m *BlobLoc) XXX_Size() int {
	return xxx_messageInfo_BlobLoc.Size(m)
}
func (m *BlobLoc) XXX_DiscardUnknown() {
	xxx_messageInfo_BlobLoc.DiscardUnknown(m)
}

var xxx_messageInfo_BlobLoc proto.InternalMessageInfo

func (m *BlobLoc) GetBlobId() []byte {
	if m != nil {
		return m.BlobId
	}
	return nil
}

func (m *BlobLoc) GetPeerId() []byte {
	if m != nil {
		return m.PeerId
	}
	return nil
}

// Blobs
type GetReq struct {
	RoutingTag           *RoutingTag `protobuf:"bytes,1,opt,name=routing_tag,json=routingTag,proto3" json:"routing_tag,omitempty"`
	BlobId               []byte      `protobuf:"bytes,2,opt,name=blob_id,json=blobId,proto3" json:"blob_id,omitempty"`
	Found                bool        `protobuf:"varint,3,opt,name=found,proto3" json:"found,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *GetReq) Reset()         { *m = GetReq{} }
func (m *GetReq) String() string { return proto.CompactTextString(m) }
func (*GetReq) ProtoMessage()    {}
func (*GetReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_bff037fc68412930, []int{7}
}

func (m *GetReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetReq.Unmarshal(m, b)
}
func (m *GetReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetReq.Marshal(b, m, deterministic)
}
func (m *GetReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetReq.Merge(m, src)
}
func (m *GetReq) XXX_Size() int {
	return xxx_messageInfo_GetReq.Size(m)
}
func (m *GetReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetReq proto.InternalMessageInfo

func (m *GetReq) GetRoutingTag() *RoutingTag {
	if m != nil {
		return m.RoutingTag
	}
	return nil
}

func (m *GetReq) GetBlobId() []byte {
	if m != nil {
		return m.BlobId
	}
	return nil
}

func (m *GetReq) GetFound() bool {
	if m != nil {
		return m.Found
	}
	return false
}

type GetRes struct {
	BlobId []byte `protobuf:"bytes,1,opt,name=blob_id,json=blobId,proto3" json:"blob_id,omitempty"`
	// Types that are valid to be assigned to Res:
	//	*GetRes_Data
	//	*GetRes_Redirect
	Res                  isGetRes_Res `protobuf_oneof:"res"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *GetRes) Reset()         { *m = GetRes{} }
func (m *GetRes) String() string { return proto.CompactTextString(m) }
func (*GetRes) ProtoMessage()    {}
func (*GetRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_bff037fc68412930, []int{8}
}

func (m *GetRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRes.Unmarshal(m, b)
}
func (m *GetRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRes.Marshal(b, m, deterministic)
}
func (m *GetRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRes.Merge(m, src)
}
func (m *GetRes) XXX_Size() int {
	return xxx_messageInfo_GetRes.Size(m)
}
func (m *GetRes) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRes.DiscardUnknown(m)
}

var xxx_messageInfo_GetRes proto.InternalMessageInfo

func (m *GetRes) GetBlobId() []byte {
	if m != nil {
		return m.BlobId
	}
	return nil
}

type isGetRes_Res interface {
	isGetRes_Res()
}

type GetRes_Data struct {
	Data []byte `protobuf:"bytes,2,opt,name=data,proto3,oneof"`
}

type GetRes_Redirect struct {
	Redirect *GetReq `protobuf:"bytes,3,opt,name=redirect,proto3,oneof"`
}

func (*GetRes_Data) isGetRes_Res() {}

func (*GetRes_Redirect) isGetRes_Res() {}

func (m *GetRes) GetRes() isGetRes_Res {
	if m != nil {
		return m.Res
	}
	return nil
}

func (m *GetRes) GetData() []byte {
	if x, ok := m.GetRes().(*GetRes_Data); ok {
		return x.Data
	}
	return nil
}

func (m *GetRes) GetRedirect() *GetReq {
	if x, ok := m.GetRes().(*GetRes_Redirect); ok {
		return x.Redirect
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*GetRes) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*GetRes_Data)(nil),
		(*GetRes_Redirect)(nil),
	}
}

func init() {
	proto.RegisterType((*RoutingTag)(nil), "RoutingTag")
	proto.RegisterType((*ListPeersReq)(nil), "ListPeersReq")
	proto.RegisterType((*ListPeersRes)(nil), "ListPeersRes")
	proto.RegisterType((*PeerInfo)(nil), "PeerInfo")
	proto.RegisterType((*ListBlobsReq)(nil), "ListBlobsReq")
	proto.RegisterType((*ListBlobsRes)(nil), "ListBlobsRes")
	proto.RegisterType((*BlobLoc)(nil), "BlobLoc")
	proto.RegisterType((*GetReq)(nil), "GetReq")
	proto.RegisterType((*GetRes)(nil), "GetRes")
}

func init() { proto.RegisterFile("blobnet.proto", fileDescriptor_bff037fc68412930) }

var fileDescriptor_bff037fc68412930 = []byte{
	// 356 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x52, 0x31, 0x6f, 0xf2, 0x30,
	0x14, 0x84, 0x00, 0x49, 0x78, 0xe1, 0xfb, 0x06, 0x8b, 0xb6, 0xe9, 0x86, 0x22, 0x21, 0x31, 0x54,
	0x19, 0xe8, 0xd0, 0xa1, 0x9d, 0x58, 0x4a, 0x24, 0x2a, 0x51, 0x8b, 0x3d, 0x4a, 0xb0, 0x43, 0x23,
	0x51, 0xbf, 0xd4, 0x36, 0x52, 0xf9, 0xf7, 0x55, 0x6c, 0x08, 0x20, 0xb5, 0x03, 0xdb, 0x3b, 0x3f,
	0xdd, 0xbd, 0xbb, 0x4b, 0xe0, 0x5f, 0xbe, 0xc5, 0x5c, 0x70, 0x1d, 0x57, 0x12, 0x35, 0x46, 0x4f,
	0x00, 0x14, 0x77, 0xba, 0x14, 0x9b, 0x55, 0xb6, 0x21, 0x37, 0xe0, 0x32, 0xa5, 0xd3, 0x92, 0x85,
	0xed, 0x51, 0x7b, 0x32, 0xa0, 0x3d, 0xa6, 0x74, 0xc2, 0x08, 0x81, 0x6e, 0x95, 0xe9, 0x8f, 0xd0,
	0x19, 0x75, 0x26, 0x5d, 0x6a, 0xe6, 0xe8, 0x05, 0x06, 0x8b, 0x52, 0xe9, 0x25, 0xe7, 0x52, 0x51,
	0xfe, 0x45, 0x1e, 0x20, 0x90, 0x56, 0x28, 0xd5, 0xd9, 0xc6, 0xf0, 0x83, 0x69, 0x10, 0x9f, 0xc4,
	0x29, 0xc8, 0x66, 0x8e, 0xde, 0x2f, 0xd8, 0x8a, 0xdc, 0x81, 0x57, 0x71, 0x2e, 0x4f, 0x97, 0xdd,
	0x1a, 0x26, 0x8c, 0x4c, 0x00, 0xec, 0x42, 0x14, 0xa8, 0x8c, 0x81, 0x60, 0xda, 0x8f, 0x6b, 0x5e,
	0x22, 0x0a, 0xa4, 0xfd, 0xea, 0x30, 0xa9, 0x28, 0x06, 0xff, 0xf8, 0x4c, 0xfe, 0x83, 0xd3, 0x28,
	0x39, 0xe5, 0xef, 0x01, 0x56, 0xd6, 0xc2, 0x6c, 0x8b, 0xf9, 0xf5, 0x01, 0xc8, 0x2d, 0xb8, 0x95,
	0xe4, 0x45, 0xf9, 0x1d, 0x3a, 0x07, 0xbf, 0x06, 0x45, 0xcb, 0x0b, 0x55, 0x45, 0xee, 0xc1, 0xd7,
	0x88, 0xe9, 0x67, 0x26, 0xf6, 0x46, 0xd2, 0xa7, 0x9e, 0x46, 0x7c, 0xcb, 0xc4, 0x9e, 0x8c, 0xa1,
	0x5f, 0x7f, 0x8b, 0x74, 0x8b, 0xeb, 0x63, 0x32, 0x3f, 0xae, 0x89, 0x0b, 0x5c, 0x53, 0x3f, 0xb7,
	0x83, 0x8a, 0x9e, 0xc1, 0x3b, 0x3c, 0xd6, 0x2d, 0x19, 0xc6, 0xa9, 0xa5, 0x1a, 0x26, 0xec, 0xbc,
	0x3e, 0xe7, 0xbc, 0xbe, 0x88, 0x83, 0xfb, 0xca, 0xf5, 0xf5, 0xf1, 0xce, 0x2e, 0x39, 0x17, 0x97,
	0x86, 0xd0, 0x2b, 0x70, 0x27, 0x58, 0xd8, 0x31, 0x61, 0x2c, 0x68, 0xce, 0xa8, 0xbf, 0x2d, 0x0e,
	0xa1, 0xcb, 0x32, 0x9d, 0x59, 0xb9, 0x79, 0x8b, 0x1a, 0x44, 0xc6, 0xe0, 0x4b, 0xce, 0x4a, 0xc9,
	0xd7, 0xda, 0x28, 0x06, 0x53, 0x2f, 0xb6, 0x86, 0xe7, 0x2d, 0xda, 0xac, 0x66, 0x3d, 0xe8, 0x48,
	0xae, 0x72, 0xd7, 0xfc, 0xb3, 0x8f, 0x3f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x62, 0x9e, 0xbd, 0x6c,
	0xc4, 0x02, 0x00, 0x00,
}
