// Code generated by protoc-gen-go. DO NOT EDIT.
// source: blobnet.proto

package blobnet

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Advertise struct {
	PeerId               []byte   `protobuf:"bytes,1,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	Prefix               []byte   `protobuf:"bytes,2,opt,name=prefix,proto3" json:"prefix,omitempty"`
	RootId               []byte   `protobuf:"bytes,3,opt,name=root_id,json=rootId,proto3" json:"root_id,omitempty"`
	Path                 []int64  `protobuf:"varint,4,rep,packed,name=path,proto3" json:"path,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Advertise) Reset()         { *m = Advertise{} }
func (m *Advertise) String() string { return proto.CompactTextString(m) }
func (*Advertise) ProtoMessage()    {}
func (*Advertise) Descriptor() ([]byte, []int) {
	return fileDescriptor_bff037fc68412930, []int{0}
}

func (m *Advertise) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Advertise.Unmarshal(m, b)
}
func (m *Advertise) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Advertise.Marshal(b, m, deterministic)
}
func (m *Advertise) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Advertise.Merge(m, src)
}
func (m *Advertise) XXX_Size() int {
	return xxx_messageInfo_Advertise.Size(m)
}
func (m *Advertise) XXX_DiscardUnknown() {
	xxx_messageInfo_Advertise.DiscardUnknown(m)
}

var xxx_messageInfo_Advertise proto.InternalMessageInfo

func (m *Advertise) GetPeerId() []byte {
	if m != nil {
		return m.PeerId
	}
	return nil
}

func (m *Advertise) GetPrefix() []byte {
	if m != nil {
		return m.Prefix
	}
	return nil
}

func (m *Advertise) GetRootId() []byte {
	if m != nil {
		return m.RootId
	}
	return nil
}

func (m *Advertise) GetPath() []int64 {
	if m != nil {
		return m.Path
	}
	return nil
}

type GetReq struct {
	BlobId               []byte   `protobuf:"bytes,1,opt,name=blob_id,json=blobId,proto3" json:"blob_id,omitempty"`
	DstPeer              []byte   `protobuf:"bytes,2,opt,name=dst_peer,json=dstPeer,proto3" json:"dst_peer,omitempty"`
	Path                 []int64  `protobuf:"varint,3,rep,packed,name=path,proto3" json:"path,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetReq) Reset()         { *m = GetReq{} }
func (m *GetReq) String() string { return proto.CompactTextString(m) }
func (*GetReq) ProtoMessage()    {}
func (*GetReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_bff037fc68412930, []int{1}
}

func (m *GetReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetReq.Unmarshal(m, b)
}
func (m *GetReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetReq.Marshal(b, m, deterministic)
}
func (m *GetReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetReq.Merge(m, src)
}
func (m *GetReq) XXX_Size() int {
	return xxx_messageInfo_GetReq.Size(m)
}
func (m *GetReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetReq proto.InternalMessageInfo

func (m *GetReq) GetBlobId() []byte {
	if m != nil {
		return m.BlobId
	}
	return nil
}

func (m *GetReq) GetDstPeer() []byte {
	if m != nil {
		return m.DstPeer
	}
	return nil
}

func (m *GetReq) GetPath() []int64 {
	if m != nil {
		return m.Path
	}
	return nil
}

type GetRes struct {
	BlobId []byte `protobuf:"bytes,1,opt,name=blob_id,json=blobId,proto3" json:"blob_id,omitempty"`
	// Types that are valid to be assigned to Res:
	//	*GetRes_Data
	//	*GetRes_Redirect
	Res                  isGetRes_Res `protobuf_oneof:"res"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *GetRes) Reset()         { *m = GetRes{} }
func (m *GetRes) String() string { return proto.CompactTextString(m) }
func (*GetRes) ProtoMessage()    {}
func (*GetRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_bff037fc68412930, []int{2}
}

func (m *GetRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRes.Unmarshal(m, b)
}
func (m *GetRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRes.Marshal(b, m, deterministic)
}
func (m *GetRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRes.Merge(m, src)
}
func (m *GetRes) XXX_Size() int {
	return xxx_messageInfo_GetRes.Size(m)
}
func (m *GetRes) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRes.DiscardUnknown(m)
}

var xxx_messageInfo_GetRes proto.InternalMessageInfo

func (m *GetRes) GetBlobId() []byte {
	if m != nil {
		return m.BlobId
	}
	return nil
}

type isGetRes_Res interface {
	isGetRes_Res()
}

type GetRes_Data struct {
	Data []byte `protobuf:"bytes,2,opt,name=data,proto3,oneof"`
}

type GetRes_Redirect struct {
	Redirect *GetReq `protobuf:"bytes,3,opt,name=redirect,proto3,oneof"`
}

func (*GetRes_Data) isGetRes_Res() {}

func (*GetRes_Redirect) isGetRes_Res() {}

func (m *GetRes) GetRes() isGetRes_Res {
	if m != nil {
		return m.Res
	}
	return nil
}

func (m *GetRes) GetData() []byte {
	if x, ok := m.GetRes().(*GetRes_Data); ok {
		return x.Data
	}
	return nil
}

func (m *GetRes) GetRedirect() *GetReq {
	if x, ok := m.GetRes().(*GetRes_Redirect); ok {
		return x.Redirect
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*GetRes) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*GetRes_Data)(nil),
		(*GetRes_Redirect)(nil),
	}
}

func init() {
	proto.RegisterType((*Advertise)(nil), "Advertise")
	proto.RegisterType((*GetReq)(nil), "GetReq")
	proto.RegisterType((*GetRes)(nil), "GetRes")
}

func init() { proto.RegisterFile("blobnet.proto", fileDescriptor_bff037fc68412930) }

var fileDescriptor_bff037fc68412930 = []byte{
	// 218 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x90, 0xc1, 0x4a, 0xc4, 0x30,
	0x10, 0x86, 0x77, 0x4d, 0x4d, 0xd7, 0x51, 0x2f, 0x41, 0xb4, 0xde, 0x96, 0x05, 0x61, 0x4f, 0x7b,
	0xd0, 0x27, 0xd0, 0x8b, 0xdb, 0xdb, 0x92, 0x17, 0x28, 0xad, 0x33, 0x62, 0x40, 0x4c, 0x9c, 0x0c,
	0xe2, 0xe3, 0xcb, 0xa4, 0xa5, 0xf4, 0xe2, 0xad, 0x5f, 0x87, 0xff, 0xfb, 0x7f, 0x02, 0xd7, 0xc3,
	0x67, 0x1c, 0xbe, 0x48, 0x0e, 0x89, 0xa3, 0xc4, 0x5d, 0x80, 0x8b, 0x67, 0xfc, 0x21, 0x96, 0x90,
	0xc9, 0xdd, 0x41, 0x9d, 0x88, 0xb8, 0x0b, 0xd8, 0xac, 0xb7, 0xeb, 0xfd, 0x95, 0xb7, 0x8a, 0x2d,
	0xba, 0x5b, 0xb0, 0x89, 0xe9, 0x3d, 0xfc, 0x36, 0x67, 0xd3, 0xff, 0x42, 0x1a, 0xe0, 0x18, 0x45,
	0x03, 0x66, 0x3c, 0x28, 0xb6, 0xe8, 0x1c, 0x54, 0xa9, 0x97, 0x8f, 0xa6, 0xda, 0x9a, 0xbd, 0xf1,
	0xe5, 0x7b, 0x77, 0x02, 0xfb, 0x4a, 0xe2, 0xe9, 0x5b, 0x63, 0xba, 0x62, 0xd1, 0xa3, 0xd8, 0xa2,
	0xbb, 0x87, 0x0d, 0x66, 0xe9, 0xb4, 0x75, 0x6a, 0xaa, 0x31, 0xcb, 0x89, 0x88, 0x67, 0xa3, 0x59,
	0x18, 0x69, 0x32, 0xe6, 0xff, 0x8d, 0x37, 0x50, 0x61, 0x2f, 0xfd, 0x68, 0x3b, 0xae, 0x7c, 0x21,
	0xf7, 0x00, 0x1b, 0x26, 0x0c, 0x4c, 0x6f, 0x52, 0x86, 0x5f, 0x3e, 0xd6, 0x87, 0x71, 0xdb, 0x71,
	0xe5, 0xe7, 0xd3, 0xcb, 0x39, 0x18, 0xa6, 0x3c, 0xd8, 0xf2, 0x54, 0x4f, 0x7f, 0x01, 0x00, 0x00,
	0xff, 0xff, 0x4a, 0x54, 0x27, 0xc0, 0x3b, 0x01, 0x00, 0x00,
}
